name: Generate Contribution Pac-Man

on:
  schedule:
    - cron: "0 0 * * *" # Roda diariamente
  workflow_dispatch: # Permite rodar manualmente

jobs:
  generate-graph:
    runs-on: ubuntu-latest
    # As permissões precisam estar definidas aqui para a automação poder escrever no repositório
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      # Esta é a nova automação que está funcionando
      - uses: VENOXV7/pacman-contribution-graph@v1.0.3
        with:
          user_name: arthurmarttins
          output_dir: output # O nome da pasta onde o gráfico será salvo

      # Este passo salva a imagem gerada de volta no seu repositório
      - name: Commit & Push
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git add output
          git commit -m "chore: update pacman contribution graph" || exit 0
          git push
