name: Generate Pac-Man Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *" # Roda todo dia à meia-noite UTC
  workflow_dispatch: # Permite que você rode manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-pacman-graph
    steps:
      - uses: actions/checkout@v3
      - uses: JieDoctor/github-readme-contribution-graph-action@v1
        with:
          user_name: arthurmarttins
          output_dir: output # Nome da pasta onde a imagem será salva

      - name: Commit & Push
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions-bot@github.com"
          git add output
          git commit -m "chore: update contribution graph" || exit 0
          git push
