name: Teste de Workflow Básico

on:
  workflow_dispatch: # Permite rodar manualmente

jobs:
  test-commit-job:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Permissão para escrever no repositório
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Criar um arquivo de teste
        run: echo "Workflow de teste executado com sucesso em $(date)" > teste.txt

      - name: Fazer o commit do arquivo de teste
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git add teste.txt
          git commit -m "CI: Adiciona arquivo de teste" || exit 0
          git push